"""initial schema: people, charts, relationships

Revision ID: b6dc9b02bc21
Revises: 
Create Date: 2026-09-11 20:36:04.673107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dc9b02bc21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_time', sa.Time(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('utc_offset_override', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('resolved_timezone', sa.String(), nullable=True),
    sa.Column('utc_offset_hours', sa.Float(), nullable=False),
    sa.Column('utc_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('julian_day_ut', sa.Float(), nullable=False),
    sa.Column('house_system', sa.String(), nullable=False),
    sa.Column('house_system_fallback_reason', sa.String(), nullable=True),
    sa.Column('houses_reliable', sa.Boolean(), nullable=False),
    sa.Column('house_cusps', sa.JSON(), nullable=False),
    sa.Column('ascendant', sa.Float(), nullable=False),
    sa.Column('midheaven', sa.Float(), nullable=False),
    sa.Column('planets', sa.JSON(), nullable=False),
    sa.Column('aspects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_a_id', sa.Integer(), nullable=False),
    sa.Column('person_b_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('generation_offset', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_a_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('charts')
    op.drop_table('people')
    # ### end Alembic commands ###
